#!/usr/bin/env bash
# Build a flashable mes-box-pi4 .img file — LXC-friendly version.
# Uses e2tools (ext4) + mtools (FAT) to inject files without loop+mount.
#
# Run on a host with: e2tools, mtools, xz, parted, sfdisk, e2fsck, resize2fs, curl
# Output: /opt/mes-box-images/mes-box-pi4-${BUILD_DATE}.img.xz
set -euo pipefail

if [[ $EUID -ne 0 ]]; then echo "Run as root"; exit 1; fi

BUILD_DATE=$(date +%Y%m%d)-final
WORK=${WORK:-/opt/mes-box-build}
SRC_URL="${SRC_URL:-https://downloads.raspberrypi.com/raspios_lite_arm64_latest}"
SRC_FILE="$WORK/raspios-lite-arm64.img.xz"
RAW_IMG="$WORK/raspios-lite-arm64.img"
OUT_DIR="${OUT_DIR:-/opt/mes-box-images}"
OUT_IMG="$OUT_DIR/mes-box-pi4-${BUILD_DATE}.img"
AGENT_DIR="${AGENT_DIR:-/opt/mock-firewalla-cloud/box-agent}"
DATA_FILES_DIR="${DATA_FILES_DIR:-/opt/mock-firewalla-cloud}"

mkdir -p "$WORK" "$OUT_DIR"

# 1. Download base Raspberry Pi OS Lite image (cached)
if [[ ! -f "$SRC_FILE" ]]; then
  echo "[1/7] Downloading Raspberry Pi OS Lite (arm64)…"
  curl -fsSL "$SRC_URL" -o "$SRC_FILE"
fi

# 2. Decompress
echo "[2/7] Decompressing base image…"
rm -f "$RAW_IMG"
xz -dkc "$SRC_FILE" > "$RAW_IMG"

# 3. Find partition offsets (from sfdisk JSON)
echo "[3/7] Reading partition layout…"
PT_JSON=$(sfdisk -J "$RAW_IMG")
P1_START=$(echo "$PT_JSON" | python3 -c 'import json,sys;d=json.load(sys.stdin);print(d["partitiontable"]["partitions"][0]["start"]*512)')
P1_SIZE=$(echo "$PT_JSON" | python3 -c 'import json,sys;d=json.load(sys.stdin);print(d["partitiontable"]["partitions"][0]["size"]*512)')
P2_START=$(echo "$PT_JSON" | python3 -c 'import json,sys;d=json.load(sys.stdin);print(d["partitiontable"]["partitions"][1]["start"]*512)')
P2_SIZE=$(echo "$PT_JSON" | python3 -c 'import json,sys;d=json.load(sys.stdin);print(d["partitiontable"]["partitions"][1]["size"]*512)')
echo "  boot: offset=$P1_START size=$P1_SIZE"
echo "  root: offset=$P2_START size=$P2_SIZE"

# Extract each partition into a separate file we can manipulate
P1_IMG="$WORK/p1-boot.img"
P2_IMG="$WORK/p2-root.img"
echo "  extracting boot partition…"
dd if="$RAW_IMG" of="$P1_IMG" bs=4M skip="$P1_START" count="$P1_SIZE" iflag=skip_bytes,count_bytes status=none
echo "  extracting rootfs partition (~2 GB, takes a moment)…"
dd if="$RAW_IMG" of="$P2_IMG" bs=4M skip="$P2_START" count="$P2_SIZE" iflag=skip_bytes,count_bytes status=none

# 4. Stage all the files we need to drop in
STAGE="$WORK/stage"
rm -rf "$STAGE"
mkdir -p "$STAGE/opt/mes-box" "$STAGE/etc/systemd/system" \
         "$STAGE/etc/systemd/system/multi-user.target.wants" \
         "$STAGE/usr/local/bin" "$STAGE/etc/update-motd.d"

cp "$AGENT_DIR/agent.js"            "$STAGE/opt/mes-box/agent.js"
cp "$DATA_FILES_DIR/oui-table.json" "$STAGE/opt/mes-box/oui-table.json"
chmod 755 "$STAGE/opt/mes-box/agent.js"

# Bake in ALL feature modules (Firewalla parity) — including simple-mode (ARP spoof)
for m in sig-engine.js sni-parser.js openvpn.js dns-stack.js multi-wan.js \
         ntp-intercept.js disturb.js bridge-mode.js upnp.js simple-mode.js \
         dhcp-mode.js router-mode.js wg-client.js \
         qos.js iot-lockdown.js quarantine.js vuln-scan.js openvpn-client.js \
         tailscale.js ipsec.js amnezia-wg.js \
         install-full.sh; do
  if [[ -f "$AGENT_DIR/$m" ]]; then
    cp "$AGENT_DIR/$m" "$STAGE/opt/mes-box/$m"
    [[ "$m" == *.sh ]] && chmod 755 "$STAGE/opt/mes-box/$m" || chmod 644 "$STAGE/opt/mes-box/$m"
    echo "  + $m baked in"
  fi
done

# Bake in pre-applied IPv4-first gai.conf so first-boot doesn't hang on AAAA-only DNS
mkdir -p "$STAGE/etc"
cat > "$STAGE/etc/gai.conf" <<'GAI'
# Generated by mes-box image builder — IPv4 prioritized so AAAA-only DNS doesn't stall apt
label  ::1/128       0
label  ::/0          1
label  2002::/16     2
label ::/96          3
label ::ffff:0:0/96  4
precedence  ::1/128       50
precedence  ::ffff:0:0/96  100
precedence  2002::/16     30
precedence ::/96          20
precedence ::/0           10
GAI

# Static resolv.conf override — bypass systemd-resolved
mkdir -p "$STAGE/etc/cloud/templates"   # Pi OS uses cloud-init in some variants
cat > "$STAGE/etc/resolv.conf" <<'RC'
nameserver 1.1.1.1
nameserver 8.8.8.8
options single-request-reopen timeout:3 attempts:2
RC

# Default Simple Mode preference — agent reads this on first boot
mkdir -p "$STAGE/etc/mes-box"
cat > "$STAGE/etc/mes-box/preferred-mode" <<'PM'
simple
PM

cat > "$STAGE/etc/systemd/system/mes-box-agent.service" <<'UNIT'
[Unit]
Description=mes Network — Box Agent
Wants=network-online.target
After=network-online.target dnsmasq.service

[Service]
ExecStart=/usr/bin/node /opt/mes-box/agent.js
Restart=always
RestartSec=10
User=root
Environment=NODE_ENV=production
Environment=MES_CLOUD=https://cloud.mes.net.lb

[Install]
WantedBy=multi-user.target
UNIT

cat > "$STAGE/etc/systemd/system/mes-box-firstboot.service" <<'UNIT'
[Unit]
Description=mes Network — first-boot setup
After=network-online.target
Wants=network-online.target
Before=mes-box-agent.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/mes-box-firstboot.sh
RemainAfterExit=true

[Install]
WantedBy=multi-user.target
UNIT

cat > "$STAGE/usr/local/bin/mes-box-firstboot.sh" <<'FB'
#!/usr/bin/env bash
# First-boot installer — STAGED:
#   Stage 0 (5s): force IPv4 DNS — many ISPs don't route IPv6
#   Stage 1 (~30-45s): critical packages, agent starts
#   Stage 2 (~5min, background): advanced features
set -e
LOG=/var/log/mes-box-firstboot.log
exec >>"$LOG" 2>&1
echo "═══════════════════════════════════════════"
echo "  mes Box first-boot install $(date -u)"
echo "═══════════════════════════════════════════"

export DEBIAN_FRONTEND=noninteractive

# Stage 0: prefer IPv4 — must run BEFORE anything tries DNS
# Many home ISPs (esp. in Lebanon/MENA) have no IPv6 route, so AAAA-first
# resolution stalls every apt call. Flip glibc precedence to IPv4-first.
echo "[Stage 0] Forcing IPv4-first DNS resolution…"
if [[ -f /etc/gai.conf ]]; then
  sed -i 's/^#precedence ::ffff:0:0\/96  100$/precedence ::ffff:0:0\/96  100/' /etc/gai.conf || true
fi
# Bypass systemd-resolved: write static resolv.conf with IPv4 resolvers
systemctl disable --now systemd-resolved 2>/dev/null || true
rm -f /etc/resolv.conf
printf "nameserver 1.1.1.1\nnameserver 8.8.8.8\noptions single-request-reopen timeout:3 attempts:2\n" > /etc/resolv.conf

# Smoke-test: can we reach the cloud over v4 now?
if ! curl -fsS -4 -o /dev/null --max-time 6 https://cloud.mes.net.lb/health 2>/dev/null; then
  echo "[Stage 0] WARN: cloud unreachable on first try; will retry during install"
fi

# Stage 1: critical only (fast — agent must start)
echo "[Stage 1] Critical packages…"
apt-get -o Acquire::ForceIPv4=true update -qq
apt-get -o Acquire::ForceIPv4=true install -y -qq curl ca-certificates iproute2 conntrack iptables nftables dnsmasq nodejs 2>&1 | tail -2 || true
if ! command -v node &>/dev/null || ! node --version 2>/dev/null | grep -qE 'v(1[89]|2[0-9])'; then
  curl -fsSL -4 https://deb.nodesource.com/setup_20.x | bash -
  apt-get -o Acquire::ForceIPv4=true install -y -qq nodejs 2>&1 | tail -2 || true
fi
echo "[Stage 1] node $(node --version 2>/dev/null || echo missing)"

# Stage 2: advanced features in background — won't block first-boot completion
echo "[Stage 2] Backgrounding advanced packages (DoH, VPN, app-DPI, etc.)…"
nohup bash -c "
  apt-get -o Acquire::ForceIPv4=true install -y -qq ebtables bridge-utils unbound dnscrypt-proxy \
    openvpn wireguard wireguard-tools tshark tcpdump nmap arping chrony \
    miniupnpd hostapd wpasupplicant speedtest-cli netcat-openbsd dsniff traceroute \
    > /var/log/mes-box-bg-install.log 2>&1 || true
  systemctl restart mes-box-agent || true
  echo '[bg-install] done at '\$(date) >> /var/log/mes-box-bg-install.log
" >/dev/null 2>&1 &
disown

# Free port 53 for our dnsmasq
systemctl disable --now systemd-resolved 2>/dev/null || true
rm -f /etc/resolv.conf
printf "nameserver 1.1.1.1\nnameserver 8.8.8.8\n" > /etc/resolv.conf

# dnsmasq baseline
mkdir -p /etc/dnsmasq.d /var/log/mes-box
cat > /etc/dnsmasq.d/mes-box.conf <<'DNS'
interface=eth0
bind-interfaces
domain-needed
bogus-priv
no-resolv
server=1.1.1.1
server=8.8.8.8
cache-size=10000
log-queries=extra
log-facility=/var/log/dnsmasq.log
no-dhcp-interface=eth0
DNS
touch /etc/dnsmasq.d/mes-box-blocks.conf
touch /etc/dnsmasq.d/mes-box-records.conf
touch /var/log/dnsmasq.log

# IP forwarding + larger conntrack table for Router/Bridge mode
cat > /etc/sysctl.d/99-mes-box.conf <<'EOF'
net.ipv4.ip_forward=1
net.netfilter.nf_conntrack_max=131072
EOF
sysctl --system >/dev/null 2>&1 || true

# Enable services
systemctl daemon-reload
systemctl enable --now dnsmasq        || true
systemctl enable --now mes-box-agent  || true
systemctl disable mes-box-firstboot.service || true

echo "═══════════════════════════════════════════"
echo "  ✅ First-boot install complete"
echo "═══════════════════════════════════════════"
FB
chmod 755 "$STAGE/usr/local/bin/mes-box-firstboot.sh"

cat > "$STAGE/etc/update-motd.d/99-mes-box" <<'MOTD'
#!/bin/sh
echo
echo "  ╔════════════════════════════════════╗"
echo "  ║    📦 mes Box — Network Guardian   ║"
echo "  ╚════════════════════════════════════╝"
[ -f /var/log/mes-box/pairing-code.txt ] && { echo; cat /var/log/mes-box/pairing-code.txt; }
echo
echo "  Logs: journalctl -u mes-box-agent -f"
echo
MOTD
chmod 755 "$STAGE/etc/update-motd.d/99-mes-box"

# 5. Inject staged files into rootfs partition via e2cp
echo "[4/7] Injecting files into rootfs (ext4) via e2cp…"

# Create directories first
e2mkdir "$P2_IMG":/opt/mes-box                                           || true
e2mkdir "$P2_IMG":/etc/systemd/system                                    || true
e2mkdir "$P2_IMG":/etc/systemd/system/multi-user.target.wants            || true
e2mkdir "$P2_IMG":/usr/local/bin                                         || true

# Copy core files
e2cp -P 755 "$STAGE/opt/mes-box/agent.js"                          "$P2_IMG":/opt/mes-box/agent.js
e2cp -P 644 "$STAGE/opt/mes-box/oui-table.json"                    "$P2_IMG":/opt/mes-box/oui-table.json
e2cp -P 644 "$STAGE/etc/systemd/system/mes-box-agent.service"      "$P2_IMG":/etc/systemd/system/mes-box-agent.service
e2cp -P 644 "$STAGE/etc/systemd/system/mes-box-firstboot.service"  "$P2_IMG":/etc/systemd/system/mes-box-firstboot.service
e2cp -P 755 "$STAGE/usr/local/bin/mes-box-firstboot.sh"            "$P2_IMG":/usr/local/bin/mes-box-firstboot.sh
e2cp -P 755 "$STAGE/etc/update-motd.d/99-mes-box"                  "$P2_IMG":/etc/update-motd.d/99-mes-box

# Copy ALL the feature modules baked into the image
for m in sig-engine.js sni-parser.js openvpn.js dns-stack.js multi-wan.js \
         ntp-intercept.js disturb.js bridge-mode.js upnp.js \
         qos.js iot-lockdown.js quarantine.js vuln-scan.js openvpn-client.js \
         tailscale.js ipsec.js amnezia-wg.js; do
  if [[ -f "$STAGE/opt/mes-box/$m" ]]; then
    e2cp -P 644 "$STAGE/opt/mes-box/$m" "$P2_IMG":/opt/mes-box/$m
    echo "  ✓ $m baked into rootfs"
  fi
done
if [[ -f "$STAGE/opt/mes-box/install-full.sh" ]]; then
  e2cp -P 755 "$STAGE/opt/mes-box/install-full.sh" "$P2_IMG":/opt/mes-box/install-full.sh
fi
# Inject pre-baked configs that make first-boot reliable
e2cp -P 644 "$STAGE/etc/gai.conf"             "$P2_IMG":/etc/gai.conf || true
e2cp -P 644 "$STAGE/etc/resolv.conf"          "$P2_IMG":/etc/resolv.conf || true
e2mkdir "$P2_IMG":/etc/mes-box || true
e2cp -P 644 "$STAGE/etc/mes-box/preferred-mode" "$P2_IMG":/etc/mes-box/preferred-mode || true
# Belt-and-suspenders: write the systemd preset to ensure both services are enabled
mkdir -p "$STAGE/etc/systemd/system-preset"
cat > "$STAGE/etc/systemd/system-preset/99-mes-box.preset" <<'PRESET'
enable mes-box-firstboot.service
enable mes-box-agent.service
enable dnsmasq.service
PRESET
e2mkdir "$P2_IMG":/etc/systemd/system-preset || true
e2cp -P 644 "$STAGE/etc/systemd/system-preset/99-mes-box.preset" "$P2_IMG":/etc/systemd/system-preset/99-mes-box.preset || true
# Triple-redundancy on enable: write to BOTH multi-user.target.wants AND default.target.wants
e2mkdir "$P2_IMG":/etc/systemd/system/default.target.wants || true
e2cp -P 644 "$STAGE/etc/systemd/system/mes-box-firstboot.service" "$P2_IMG":/etc/systemd/system/default.target.wants/mes-box-firstboot.service || true

# Symlinks for systemd "enable" — e2tools can't make symlinks; we cheat by writing
# a placeholder that systemd will treat the same way: drop a .service in
# /etc/systemd/system/multi-user.target.wants/ pointing to absolute path.
# Actually e2tools CAN make symlinks via e2ln if available. Try; fall back to copy.
if e2ln -h 2>&1 | head -1 | grep -q usage; then
  e2ln "$P2_IMG" /etc/systemd/system/mes-box-agent.service /etc/systemd/system/multi-user.target.wants/mes-box-agent.service
  e2ln "$P2_IMG" /etc/systemd/system/mes-box-firstboot.service /etc/systemd/system/multi-user.target.wants/mes-box-firstboot.service
else
  # Plan B: just copy the service file (works because absolute path in WantedBy)
  e2cp -P 644 "$STAGE/etc/systemd/system/mes-box-agent.service"    "$P2_IMG":/etc/systemd/system/multi-user.target.wants/mes-box-agent.service
  e2cp -P 644 "$STAGE/etc/systemd/system/mes-box-firstboot.service" "$P2_IMG":/etc/systemd/system/multi-user.target.wants/mes-box-firstboot.service
fi

# 6. Touch /boot/ssh so SSH is enabled + create userconf.txt (pi:raspberry pre-baked)
echo "[5/7] Enabling SSH + pre-creating pi user via boot partition…"
echo "drive c: file=\"$P1_IMG\" exclusive" > "$WORK/.mtoolsrc"
export MTOOLSRC="$WORK/.mtoolsrc"
# /boot/ssh marker — enables sshd at boot
echo "" | mcopy -o - c:ssh   2>/dev/null || true
# /boot/userconf.txt — creates `pi` user with password `raspberry` on first boot.
# Pi OS Bookworm needs this; without it sshd has no user to authenticate as.
PWHASH=$(echo -n 'raspberry' | openssl passwd -6 -stdin)
printf "pi:%s\n" "$PWHASH" > "$WORK/userconf.txt"
mcopy -o "$WORK/userconf.txt" c:userconf.txt 2>/dev/null || true
rm -f "$WORK/userconf.txt"

# 7. Re-assemble the partition images back into the whole disk image
echo "[6/7] Re-assembling final image…"
dd if="$P1_IMG" of="$RAW_IMG" bs=4M seek="$P1_START" conv=notrunc oflag=seek_bytes status=none
dd if="$P2_IMG" of="$RAW_IMG" bs=4M seek="$P2_START" conv=notrunc oflag=seek_bytes status=none

mv "$RAW_IMG" "$OUT_IMG"

echo "[7/7] Compressing to .img.xz…"
xz -T0 -6 -f "$OUT_IMG"
sha256sum "$OUT_IMG.xz" > "$OUT_IMG.xz.sha256"

ls -lh "$OUT_IMG.xz" "$OUT_IMG.xz.sha256"
echo "✅ Done: $OUT_IMG.xz"
