// suricata.js — Suricata IDS/IPS box-side wrapper (Tier 2 Feature A)
//
// Exposes a clean API the agent calls to install, configure, run, monitor,
// and update rules for Suricata. The cloud-side ships ET-OPEN ruleset events
// every minute via tailEvents() → POST /api/box/ids-alerts.
//
// Behaviour summary:
//   install()           — apt-install suricata + jq (idempotent; quick path on Pi where it's pre-installed)
//   configure()         — writes a minimal /etc/suricata/suricata.yaml pointing at LAN_IF + EVE JSON output
//   updateRules()       — wgets ET-OPEN tarball, extracts to /etc/suricata/rules/, reloads suricata
//   start()/stop()      — systemctl wrappers
//   getStatus()         — returns {running, rule_count, last_update, eve_size}
//   tailEvents(N)       — tails last N lines of /var/log/suricata/eve.json, returns alert events only
//
// Cron: daily refresh of ET-OPEN rules is set up by the agent on boot (not here).

'use strict';

const fs = require('fs');
const path = require('path');
const { execSync, spawn } = require('child_process');

const RULES_DIR = '/etc/suricata/rules';
const SURICATA_CONF = '/etc/suricata/suricata.yaml';
const EVE_LOG = '/var/log/suricata/eve.json';
const ET_OPEN_URL = 'https://rules.emergingthreats.net/open/suricata-7.0/emerging.rules.tar.gz';
const TARBALL_TMP = '/tmp/et-open.tar.gz';
const LAST_UPDATE_FILE = '/var/lib/mes-box/suricata-last-update';

function sh(cmd, opts = {}) {
  return execSync(cmd, { encoding: 'utf8', timeout: 120_000, ...opts });
}

function isInstalled() {
  try {
    execSync('command -v suricata >/dev/null 2>&1', { stdio: 'ignore' });
    return true;
  } catch { return false; }
}

function install() {
  if (isInstalled()) return { ok: true, already_installed: true };
  try {
    // ForceIPv4 because some ISPs (and our Pi over Wireguard) have flaky v6.
    execSync('DEBIAN_FRONTEND=noninteractive apt-get update -y -o Acquire::ForceIPv4=true', { encoding: 'utf8', timeout: 180_000 });
    execSync('DEBIAN_FRONTEND=noninteractive apt-get install -y -o Acquire::ForceIPv4=true suricata jq', { encoding: 'utf8', timeout: 300_000 });
    return { ok: true, installed: true };
  } catch (e) {
    return { ok: false, error: e.message.slice(0, 500) };
  }
}

// Writes a minimal suricata.yaml. Keeps stock classification/reference.config.
function configure(iface) {
  const ifaceName = (iface || 'eth0').replace(/[^a-z0-9]/gi, '');
  try { fs.mkdirSync(RULES_DIR, { recursive: true }); } catch {}
  try { fs.mkdirSync('/var/log/suricata', { recursive: true }); } catch {}
  const yaml = `%YAML 1.1
---
# mes Network — Suricata config (auto-generated by box agent)
# Edit at your own risk; agent will overwrite on next install/config tick.

vars:
  address-groups:
    HOME_NET: "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
    EXTERNAL_NET: "!$HOME_NET"

default-rule-path: ${RULES_DIR}
rule-files:
  - suricata.rules
  - emerging-*.rules

classification-file: /etc/suricata/classification.config
reference-config-file: /etc/suricata/reference.config

af-packet:
  - interface: ${ifaceName}
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: yes
    use-mmap: yes
    tpacket-v3: yes

outputs:
  - eve-log:
      enabled: yes
      filetype: regular
      filename: ${EVE_LOG}
      types:
        - alert:
            metadata: yes
            tagged-packets: yes
        - flow

logging:
  default-log-level: notice
  outputs:
    - console:
        enabled: no
    - file:
        enabled: yes
        level: info
        filename: /var/log/suricata/suricata.log
`;
  try {
    let prev = '';
    try { prev = fs.readFileSync(SURICATA_CONF, 'utf8'); } catch {}
    if (prev !== yaml) {
      fs.writeFileSync(SURICATA_CONF, yaml);
    }
    return { ok: true, iface: ifaceName, conf: SURICATA_CONF };
  } catch (e) {
    return { ok: false, error: e.message };
  }
}

function updateRules() {
  try { fs.mkdirSync(RULES_DIR, { recursive: true }); } catch {}
  try { fs.mkdirSync('/var/lib/mes-box', { recursive: true }); } catch {}
  try {
    sh(`curl -fsSL -4 --max-time 90 "${ET_OPEN_URL}" -o "${TARBALL_TMP}"`);
    // Extract just the .rules + classification.config + reference.config we need.
    // ET-OPEN ships a top-level `rules/` directory with hundreds of *.rules files.
    sh(`tar -xzf "${TARBALL_TMP}" -C /tmp/`);
    // The tarball extracts to /tmp/rules/. Move into place.
    if (fs.existsSync('/tmp/rules')) {
      sh(`cp -f /tmp/rules/*.rules ${RULES_DIR}/ 2>/dev/null || true`);
      // Always ship a stub suricata.rules so rule-files: works even with zero ET rules
      if (!fs.existsSync(path.join(RULES_DIR, 'suricata.rules'))) {
        fs.writeFileSync(path.join(RULES_DIR, 'suricata.rules'), '# placeholder — ET-OPEN rules in emerging-*.rules\n');
      }
      sh(`cp -f /tmp/rules/*.config /etc/suricata/ 2>/dev/null || true`);
    }
    try { fs.unlinkSync(TARBALL_TMP); } catch {}
    const count = countRules();
    fs.writeFileSync(LAST_UPDATE_FILE, String(Date.now()));
    // Hot reload via suricatasc if available, else SIGUSR2, else full restart
    try {
      sh('suricatasc -c reload-rules 2>/dev/null || pkill -USR2 suricata 2>/dev/null || systemctl reload suricata 2>/dev/null || systemctl restart suricata');
    } catch {}
    return { ok: true, rule_count: count, last_update: Date.now() };
  } catch (e) {
    return { ok: false, error: e.message.slice(0, 500) };
  }
}

function countRules() {
  try {
    const files = fs.readdirSync(RULES_DIR).filter(f => f.endsWith('.rules'));
    let total = 0;
    for (const f of files) {
      try {
        const txt = fs.readFileSync(path.join(RULES_DIR, f), 'utf8');
        for (const line of txt.split('\n')) {
          const l = line.trim();
          if (!l || l.startsWith('#')) continue;
          total++;
        }
      } catch {}
    }
    return total;
  } catch { return 0; }
}

function start() {
  try {
    sh('systemctl enable --now suricata 2>&1');
    return { ok: true, running: true };
  } catch (e) {
    return { ok: false, error: e.message.slice(0, 300) };
  }
}

function stop() {
  try {
    sh('systemctl stop suricata 2>&1');
    return { ok: true, running: false };
  } catch (e) {
    return { ok: false, error: e.message.slice(0, 300) };
  }
}

function isRunning() {
  try {
    execSync('systemctl is-active --quiet suricata');
    return true;
  } catch { return false; }
}

function getStatus() {
  const running = isRunning();
  let eve_size = 0;
  try { eve_size = fs.statSync(EVE_LOG).size; } catch {}
  let last_update = 0;
  try { last_update = parseInt(fs.readFileSync(LAST_UPDATE_FILE, 'utf8')) || 0; } catch {}
  return {
    installed: isInstalled(),
    running,
    rule_count: countRules(),
    last_update,
    eve_size,
    eve_path: EVE_LOG,
  };
}

// Tail last N alert events from EVE JSON. EVE mixes alert/flow/dns rows in
// the same file, so we grep for the `event_type":"alert"` substring first
// (much cheaper than parsing thousands of flow lines) and parse just those.
function tailEvents(limit = 100) {
  const n = Math.min(Math.max(parseInt(limit) || 100, 1), 1000);
  try {
    if (!fs.existsSync(EVE_LOG)) return [];
    // grep last N matches: use grep + tail. Fall back to a full grep if needed.
    let out;
    try {
      out = execSync(
        `grep -F '"event_type":"alert"' ${EVE_LOG} 2>/dev/null | tail -n ${n}`,
        { encoding: 'utf8', maxBuffer: 8 * 1024 * 1024, timeout: 10_000 }
      );
    } catch (e) {
      out = '';
    }
    const events = [];
    for (const line of out.split('\n')) {
      if (!line.trim()) continue;
      try {
        const ev = JSON.parse(line);
        if (ev.event_type === 'alert') events.push(ev);
      } catch {}
      if (events.length >= n) break;
    }
    return events;
  } catch (e) {
    return [];
  }
}

module.exports = {
  install, configure, updateRules,
  start, stop, getStatus, tailEvents,
  isInstalled, isRunning, countRules,
  EVE_LOG, RULES_DIR,
};
