'use strict';
/*
 * tailscale.js — Tailscale / Headscale native client integration.
 *
 * Tailscale is a wildly popular mesh VPN using WireGuard with NAT
 * traversal and a central control plane. This module wraps the official
 * `tailscale` CLI so the customer can join their tailnet from the box,
 * advertise their LAN as a subnet route, and even use the box as an
 * exit node — without us needing to compile anything.
 *
 * Limitations:
 *   - Requires the `tailscale` package; install() installs the official
 *     repo via https://tailscale.com/install.sh.
 *   - Auth keys must be generated by the user at
 *     https://login.tailscale.com/admin/settings/keys (reusable + ephemeral
 *     keys both work).
 *   - Self-hosted Headscale works too — just pass `login_server` to up().
 *
 * Public API:
 *   install()                       -> { ok, version? }
 *   up({auth_key, hostname,
 *       advertise_routes, accept_routes, accept_dns,
 *       exit_node, login_server})   -> { ok, output }
 *   down()                          -> { ok }
 *   getStatus()                     -> parsed JSON status
 *   setRoutes(cidrs)                -> re-runs up with new routes
 *   logout()                        -> { ok }
 */

const fs = require('fs');
const { execSync } = require('child_process');

function sh(cmd, opts = {}) {
  try { return execSync(cmd, { encoding: 'utf8', timeout: 20_000, stdio: ['ignore', 'pipe', 'pipe'], ...opts }).trim(); }
  catch (e) { return null; }
}

function shThrow(cmd, opts = {}) {
  return execSync(cmd, { encoding: 'utf8', timeout: 60_000, stdio: ['ignore', 'pipe', 'pipe'], ...opts }).trim();
}

function have(bin) { return !!sh(`which ${bin}`); }

// ─── public API ─────────────────────────────────────────────────────────

function install() {
  if (have('tailscale')) {
    const v = sh('tailscale version | head -1') || '';
    return { ok: true, already_installed: true, version: v };
  }
  // Run official Tailscale installer. Idempotent.
  try {
    // 60s timeout — installer hits apt + adds repo + installs package
    shThrow('curl -fsSL https://tailscale.com/install.sh | sh', { timeout: 180_000 });
  } catch (e) {
    return { ok: false, error: 'install_failed', detail: (e.message || '').slice(0, 500) };
  }
  if (!have('tailscale')) {
    return { ok: false, error: 'tailscale_not_in_path_after_install' };
  }
  // Make sure the daemon is running before any `up`/`status` call
  try { sh('systemctl enable --now tailscaled 2>/dev/null'); } catch {}
  const v = sh('tailscale version | head -1') || '';
  return { ok: true, installed: true, version: v };
}

function _buildUpArgs(opts = {}) {
  const args = ['up'];
  if (opts.auth_key) args.push(`--auth-key=${opts.auth_key}`);
  if (opts.hostname) args.push(`--hostname=${opts.hostname}`);
  if (opts.login_server) args.push(`--login-server=${opts.login_server}`);
  if (Array.isArray(opts.advertise_routes) && opts.advertise_routes.length) {
    args.push(`--advertise-routes=${opts.advertise_routes.join(',')}`);
  } else if (typeof opts.advertise_routes === 'string' && opts.advertise_routes.trim()) {
    args.push(`--advertise-routes=${opts.advertise_routes.trim()}`);
  }
  if (opts.accept_routes) args.push('--accept-routes');
  if (opts.accept_dns === false) args.push('--accept-dns=false');
  if (opts.exit_node) args.push(`--exit-node=${opts.exit_node}`);
  // --reset clears any leftover state from prior `up` invocations (route
  // advertisements etc.) so the new state matches what the customer asked.
  args.push('--reset');
  // Don't prompt — fail fast if anything is interactive.
  args.push('--timeout=30s');
  return args;
}

function up(opts = {}) {
  if (!have('tailscale')) return { ok: false, error: 'tailscale_not_installed', hint: 'Run install() first' };
  if (!opts.auth_key) return { ok: false, error: 'auth_key_required', hint: 'Generate at https://login.tailscale.com/admin/settings/keys' };

  // Make sure tailscaled is running
  try { sh('systemctl start tailscaled 2>/dev/null'); } catch {}

  const args = _buildUpArgs(opts);
  // Quote each arg for the shell. tailscale CLI doesn't need shell escaping of
  // the auth key contents (alphanumeric + dashes), but we still quote.
  const cmd = 'tailscale ' + args.map(a => `'${String(a).replace(/'/g, "'\\''")}'`).join(' ');
  try {
    const out = shThrow(cmd, { timeout: 45_000 });
    return { ok: true, output: out.slice(0, 2000) };
  } catch (e) {
    return { ok: false, error: 'up_failed', detail: ((e.stderr || e.stdout || e.message) + '').slice(0, 1000) };
  }
}

function down() {
  if (!have('tailscale')) return { ok: false, error: 'tailscale_not_installed' };
  try { sh('tailscale down'); } catch {}
  return { ok: true };
}

function logout() {
  if (!have('tailscale')) return { ok: false, error: 'tailscale_not_installed' };
  try { sh('tailscale logout'); } catch {}
  return { ok: true };
}

function getStatus() {
  if (!have('tailscale')) return { ok: false, error: 'tailscale_not_installed', installed: false };
  const raw = sh('tailscale status --json 2>/dev/null');
  if (!raw) {
    // Daemon may be off, or never authed.
    const ver = sh('tailscale version | head -1') || '';
    return { ok: true, installed: true, version: ver, state: 'NeedsLogin', peers: [], self: null };
  }
  let j;
  try { j = JSON.parse(raw); } catch (e) { return { ok: false, error: 'parse_failed', detail: e.message }; }
  const self = j.Self || {};
  const peers = j.Peer ? Object.values(j.Peer).map(p => ({
    id: p.ID,
    name: p.HostName || p.DNSName || '',
    dns_name: p.DNSName || '',
    ip: (p.TailscaleIPs || [])[0] || '',
    os: p.OS || '',
    online: !!p.Online,
    last_seen: p.LastSeen || null,
    rx_bytes: p.RxBytes || 0,
    tx_bytes: p.TxBytes || 0,
    exit_node: !!p.ExitNode,
    exit_node_option: !!p.ExitNodeOption,
  })) : [];
  return {
    ok: true,
    installed: true,
    version: j.Version || '',
    state: j.BackendState || 'Unknown',
    self: {
      id: self.ID || '',
      name: self.HostName || '',
      dns_name: self.DNSName || '',
      ip: (self.TailscaleIPs || [])[0] || '',
      os: self.OS || '',
      online: !!self.Online,
    },
    auth_url: j.AuthURL || null,
    magic_dns: j.CurrentTailnet && j.CurrentTailnet.MagicDNSEnabled || false,
    peers,
  };
}

function setRoutes(cidrs) {
  if (!have('tailscale')) return { ok: false, error: 'tailscale_not_installed' };
  let list = [];
  if (Array.isArray(cidrs)) list = cidrs;
  else if (typeof cidrs === 'string') list = cidrs.split(',').map(s => s.trim()).filter(Boolean);
  // Validate each is a proper CIDR-looking string
  for (const c of list) {
    if (!/^\d{1,3}(?:\.\d{1,3}){3}\/\d{1,2}$/.test(c) && !/^[a-f0-9:]+\/\d{1,3}$/i.test(c)) {
      return { ok: false, error: 'bad_cidr', detail: c };
    }
  }
  // `tailscale set` is the modern way to update routes without re-authing.
  const arg = list.length ? `--advertise-routes=${list.join(',')}` : '--advertise-routes=';
  try {
    const out = shThrow(`tailscale set ${arg}`, { timeout: 20_000 });
    return { ok: true, advertised: list, output: out.slice(0, 1000) };
  } catch (e) {
    return { ok: false, error: 'set_failed', detail: ((e.stderr || e.stdout || e.message) + '').slice(0, 500) };
  }
}

module.exports = {
  install,
  up,
  down,
  logout,
  getStatus,
  setRoutes,
};
