// upnp.js - miniupnpd manager for Pi-based router (Firewalla-style)
//
// Manages a miniupnpd instance bound to the LAN interface so that LAN
// clients (Xbox/PlayStation/peer-to-peer apps/VoIP) can auto-request
// port forwards via UPnP IGD / NAT-PMP.
//
// Responsibilities:
//   - apt install miniupnpd (idempotent)
//   - Render /etc/miniupnpd/miniupnpd.conf from runtime opts
//   - Start/stop the systemd service
//   - Parse /var/run/miniupnpd.leases for active mappings
//   - Revoke a mapping by ext_port/proto (using upnpc-style cleanup, or by
//     editing the lease file + reload + iptables flush of the chain)
//   - Maintain a deny list to block specific clients from UPnP

'use strict';

const { execSync, spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const CONF_PATH = '/etc/miniupnpd/miniupnpd.conf';
const DEFAULT_LEASE_FILE = '/var/run/miniupnpd.leases';
const STATE_FILE = '/var/lib/firewalla/upnp-state.json';
const SERVICE = 'miniupnpd';

// ---------- small utils ----------

function sh(cmd, opts) {
  try {
    return execSync(cmd, Object.assign({ encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }, opts || {}));
  } catch (e) {
    const err = new Error(`cmd failed: ${cmd}: ${e.message}`);
    err.stdout = e.stdout && e.stdout.toString();
    err.stderr = e.stderr && e.stderr.toString();
    err.status = e.status;
    throw err;
  }
}

function shTry(cmd) {
  try { return { ok: true, out: sh(cmd) }; }
  catch (e) { return { ok: false, err: e }; }
}

function ensureDir(p) {
  fs.mkdirSync(p, { recursive: true });
}

function readState() {
  try { return JSON.parse(fs.readFileSync(STATE_FILE, 'utf8')); }
  catch (_) { return { deny_subnets: [], allow_subnets: [], opts: null }; }
}

function writeState(s) {
  ensureDir(path.dirname(STATE_FILE));
  fs.writeFileSync(STATE_FILE, JSON.stringify(s, null, 2));
}

function isInstalled() {
  const r = shTry('dpkg -s miniupnpd 2>/dev/null | grep -q "Status: install ok installed"');
  return r.ok;
}

function isServiceActive() {
  const r = shTry(`systemctl is-active --quiet ${SERVICE}`);
  return r.ok;
}

// ---------- config rendering ----------

function renderConfig(opts, denyList, allowList) {
  const wan = opts.wan_iface;
  const lan = opts.lan_iface;
  const leaseFile = opts.lease_file || DEFAULT_LEASE_FILE;

  const lines = [];
  lines.push('# Generated by box-agent/upnp.js - do not edit by hand');
  lines.push(`ext_ifname=${wan}`);
  lines.push(`listening_ip=${lan}`);
  lines.push('enable_natpmp=yes');
  lines.push('enable_upnp=yes');
  lines.push('');
  lines.push('# Bandwidth advertised to clients (informational, not enforced)');
  lines.push('bitrate_up=10000000');
  lines.push('bitrate_down=100000000');
  lines.push('');
  lines.push('# Tighten behaviour: only allow clients to map their own IP');
  lines.push('secure_mode=yes');
  lines.push('system_uptime=yes');
  lines.push('');
  lines.push(`lease_file=${leaseFile}`);
  lines.push('');
  lines.push('# Default mapping lifetime if client did not specify (seconds)');
  lines.push('min_lifetime=120');
  lines.push('max_lifetime=86400');
  lines.push('');

  // Deny entries first - miniupnpd evaluates ACLs top-down
  lines.push('# --- deny list (blocked clients) ---');
  for (const ip of (denyList || [])) {
    const cidr = ip.includes('/') ? ip : `${ip}/32`;
    lines.push(`deny 0-65535 ${cidr} 0-65535`);
  }
  lines.push('');

  // Allow list - default to RFC1918 ranges if none provided
  lines.push('# --- allow list ---');
  const allows = (allowList && allowList.length)
    ? allowList
    : ['192.168.0.0/16', '10.0.0.0/8', '172.16.0.0/12'];
  for (const cidr of allows) {
    lines.push(`allow 1024-65535 ${cidr} 1024-65535`);
  }
  lines.push('');

  // Final catch-all deny (matches the sample in the spec)
  lines.push('# --- catch-all ---');
  lines.push('deny 0-65535 0.0.0.0/0 0-65535');
  lines.push('');

  return lines.join('\n');
}

function writeConfigIfChanged(content) {
  let cur = '';
  try { cur = fs.readFileSync(CONF_PATH, 'utf8'); } catch (_) {}
  if (cur === content) return false;
  ensureDir(path.dirname(CONF_PATH));
  fs.writeFileSync(CONF_PATH, content);
  return true;
}

// ---------- lease parsing ----------

function parseLeaseFile(leaseFile) {
  let raw;
  try { raw = fs.readFileSync(leaseFile, 'utf8'); }
  catch (_) { return []; }

  const out = [];
  for (const line of raw.split('\n')) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    // Format: proto:ext_port:int_ip:int_port:lease_end_ts:description
    // Some miniupnpd builds use a leading char for direction; tolerate it.
    const parts = t.split(':');
    if (parts.length < 5) continue;

    let proto = parts[0].toUpperCase();
    if (proto.length === 1) proto = parts[1] && /^(TCP|UDP)$/i.test(parts[1]) ? parts[1].toUpperCase() : proto;

    // Re-split robustly: assume 6 fields exactly
    let p, ext, ip, ip2, ts, desc;
    if (parts.length >= 6) {
      [p, ext, ip, ip2, ts, ...desc] = parts;
      desc = desc.join(':');
    } else {
      continue;
    }

    const entry = {
      proto: String(p).toUpperCase(),
      ext_port: parseInt(ext, 10),
      int_ip: ip,
      int_port: parseInt(ip2, 10),
      lease_end_ts: parseInt(ts, 10),
      description: desc || '',
      client_ip: ip,
      ts: parseInt(ts, 10),
      lease_duration_s: Math.max(0, parseInt(ts, 10) - Math.floor(Date.now() / 1000)),
    };
    if (Number.isFinite(entry.ext_port) && Number.isFinite(entry.int_port)) {
      out.push(entry);
    }
  }
  return out;
}

// ---------- iptables cleanup for a removed mapping ----------

function flushMappingIptables(extPort, proto, intIp, intPort) {
  const p = String(proto).toLowerCase();
  // miniupnpd inserts into chains MINIUPNPD (filter) and MINIUPNPD (nat).
  // Best-effort delete; ignore failures.
  shTry(`iptables -t nat -D MINIUPNPD -p ${p} --dport ${extPort} -j DNAT --to-destination ${intIp}:${intPort}`);
  shTry(`iptables -D MINIUPNPD -p ${p} -d ${intIp} --dport ${intPort} -j ACCEPT`);
}

// ---------- public API ----------

function installAndStart(opts) {
  if (!opts || !opts.wan_iface || !opts.lan_iface) {
    throw new Error('installAndStart requires { wan_iface, lan_iface }');
  }

  // 1. install miniupnpd if missing
  if (!isInstalled()) {
    sh('DEBIAN_FRONTEND=noninteractive apt-get update -qq');
    sh('DEBIAN_FRONTEND=noninteractive apt-get install -y -qq miniupnpd');
  }

  // 2. ensure required iptables chain exists (miniupnpd expects it)
  shTry('iptables -t nat -N MINIUPNPD');
  shTry('iptables -N MINIUPNPD');
  // Make sure the chain is referenced from PREROUTING/FORWARD
  const natChk = shTry('iptables -t nat -C PREROUTING -i ' + opts.wan_iface + ' -j MINIUPNPD');
  if (!natChk.ok) shTry(`iptables -t nat -A PREROUTING -i ${opts.wan_iface} -j MINIUPNPD`);
  const fwdChk = shTry('iptables -C FORWARD -i ' + opts.wan_iface + ' ! -o ' + opts.wan_iface + ' -j MINIUPNPD');
  if (!fwdChk.ok) shTry(`iptables -A FORWARD -i ${opts.wan_iface} ! -o ${opts.wan_iface} -j MINIUPNPD`);

  // 3. merge state and render config
  const state = readState();
  if (Array.isArray(opts.deny_subnets)) state.deny_subnets = opts.deny_subnets.slice();
  if (Array.isArray(opts.allow_subnets)) state.allow_subnets = opts.allow_subnets.slice();
  state.opts = {
    wan_iface: opts.wan_iface,
    lan_iface: opts.lan_iface,
    lease_file: opts.lease_file || DEFAULT_LEASE_FILE,
  };
  writeState(state);

  const conf = renderConfig(state.opts, state.deny_subnets, state.allow_subnets);
  const changed = writeConfigIfChanged(conf);

  // 4. ensure lease file exists & is writable
  try {
    if (!fs.existsSync(state.opts.lease_file)) fs.writeFileSync(state.opts.lease_file, '');
  } catch (_) {}

  // 5. start / restart service
  sh(`systemctl enable ${SERVICE}`);
  if (!isServiceActive()) {
    sh(`systemctl start ${SERVICE}`);
  } else if (changed) {
    sh(`systemctl restart ${SERVICE}`);
  }

  return { ok: true, restarted: changed, conf_path: CONF_PATH };
}

function stop() {
  if (isServiceActive()) sh(`systemctl stop ${SERVICE}`);
  // leave iptables chain in place; flush its rules so no stale mappings linger
  shTry('iptables -t nat -F MINIUPNPD');
  shTry('iptables -F MINIUPNPD');
  return { ok: true };
}

function getStatus() {
  const running = isServiceActive();
  let version = null;
  const v = shTry('miniupnpd --version 2>&1 | head -n1');
  if (v.ok) {
    const m = v.out.match(/(\d+\.\d+(?:\.\d+)?)/);
    if (m) version = m[1];
  }

  let uptime_s = 0;
  if (running) {
    const r = shTry(`systemctl show ${SERVICE} --property=ActiveEnterTimestampMonotonic --value`);
    if (r.ok) {
      // ActiveEnterTimestampMonotonic is in microseconds since boot
      const enteredUs = parseInt(r.out.trim(), 10);
      const upR = shTry('cat /proc/uptime');
      if (upR.ok && Number.isFinite(enteredUs)) {
        const bootUptimeS = parseFloat(upR.out.split(' ')[0]);
        uptime_s = Math.max(0, Math.round(bootUptimeS - enteredUs / 1e6));
      }
    }
  }

  const state = readState();
  const leaseFile = (state.opts && state.opts.lease_file) || DEFAULT_LEASE_FILE;
  const mappings = parseLeaseFile(leaseFile);

  return {
    running,
    version,
    uptime_s,
    active_mappings_count: mappings.length,
  };
}

function listMappings() {
  const state = readState();
  const leaseFile = (state.opts && state.opts.lease_file) || DEFAULT_LEASE_FILE;
  return parseLeaseFile(leaseFile);
}

function removeMapping(extPort, proto) {
  const portN = parseInt(extPort, 10);
  const protoU = String(proto || '').toUpperCase();
  if (!Number.isFinite(portN) || !['TCP', 'UDP'].includes(protoU)) {
    throw new Error('removeMapping requires (ext_port:number, proto:"TCP"|"UDP")');
  }

  const state = readState();
  const leaseFile = (state.opts && state.opts.lease_file) || DEFAULT_LEASE_FILE;
  const mappings = parseLeaseFile(leaseFile);
  const target = mappings.find(m => m.ext_port === portN && m.proto === protoU);

  // Rewrite lease file without the matching entry
  let raw = '';
  try { raw = fs.readFileSync(leaseFile, 'utf8'); } catch (_) {}
  const kept = raw.split('\n').filter(line => {
    const t = line.trim();
    if (!t || t.startsWith('#')) return true;
    const parts = t.split(':');
    if (parts.length < 6) return true;
    const p = parts[0].toUpperCase();
    const e = parseInt(parts[1], 10);
    return !(p === protoU && e === portN);
  });
  fs.writeFileSync(leaseFile, kept.join('\n'));

  // Drop the iptables rule (best-effort)
  if (target) {
    flushMappingIptables(target.ext_port, target.proto, target.int_ip, target.int_port);
  }

  // Reload miniupnpd so its in-memory table reflects the lease file
  if (isServiceActive()) shTry(`systemctl reload-or-restart ${SERVICE}`);

  return { ok: true, removed: !!target };
}

function blockClientFromUpnp(ip) {
  if (!ip || typeof ip !== 'string') throw new Error('blockClientFromUpnp requires ip');
  const state = readState();
  state.deny_subnets = state.deny_subnets || [];
  if (!state.deny_subnets.includes(ip)) state.deny_subnets.push(ip);
  writeState(state);

  if (state.opts) {
    const conf = renderConfig(state.opts, state.deny_subnets, state.allow_subnets);
    if (writeConfigIfChanged(conf) && isServiceActive()) {
      sh(`systemctl restart ${SERVICE}`);
    }
  }

  // Also nuke any active mappings already owned by that client
  const leaseFile = (state.opts && state.opts.lease_file) || DEFAULT_LEASE_FILE;
  const mappings = parseLeaseFile(leaseFile);
  for (const m of mappings) {
    if (m.int_ip === ip) {
      try { removeMapping(m.ext_port, m.proto); } catch (_) {}
    }
  }
  return { ok: true, deny_subnets: state.deny_subnets };
}

function unblockClient(ip) {
  if (!ip || typeof ip !== 'string') throw new Error('unblockClient requires ip');
  const state = readState();
  state.deny_subnets = (state.deny_subnets || []).filter(x => x !== ip && x !== `${ip}/32`);
  writeState(state);

  if (state.opts) {
    const conf = renderConfig(state.opts, state.deny_subnets, state.allow_subnets);
    if (writeConfigIfChanged(conf) && isServiceActive()) {
      sh(`systemctl restart ${SERVICE}`);
    }
  }
  return { ok: true, deny_subnets: state.deny_subnets };
}

module.exports = {
  installAndStart,
  stop,
  getStatus,
  listMappings,
  removeMapping,
  blockClientFromUpnp,
  unblockClient,
};
